# Form implementation generated from reading ui file 'C:\Users\hoduc\PycharmProjects\BVGD_Project\src\app\ui\ThongBaoThongTuyenBHYT.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 300)
        Dialog.setStyleSheet("QLabel {\n"
"color: rgb(0, 181, 133) ;\n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.maKetQua = QtWidgets.QLabel(parent=Dialog)
        self.maKetQua.setObjectName("maKetQua")
        self.verticalLayout.addWidget(self.maKetQua)
        self.ghiChu = QtWidgets.QLabel(parent=Dialog)
        self.ghiChu.setStyleSheet("")
        self.ghiChu.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.ghiChu.setWordWrap(True)
        self.ghiChu.setObjectName("ghiChu")
        self.verticalLayout.addWidget(self.ghiChu)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Thông báo kết quả thông tuyến"))
        self.maKetQua.setText(_translate("Dialog", "Mã kết quả [000]: Thẻ còn giá trị sử dụng"))
        self.ghiChu.setText(_translate("Dialog", "\'Thẻ còn giá trị sử dụng! Họ tên : Nguyễn Văn A, Ngày sinh: 01/01/1999, Giới tính : Nam! (ĐC: 123 Đường Nơ Trang Long, Phường Gia Định, Quận Bình Thạnh, Thành phố Hồ Chí Minh; Nơi KCBBĐ: 79030; Hạn thẻ: 01/01/2026 - 31/12/2026; Thời điểm đủ 5 năm liên tục: 01/01/2015).\'"))
